config/routes.rb
Rails.application.routes.draw do

 root to: 'homes#top'
 resources :books

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    # Viewへ渡すためのインスタンス変数に空のModelオブジェクトを生成する。
    @book = Book.new
  end

  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    @book = Book.new(book_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    if @book.save
   # 4. トップ画面へリダイレクト
      redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
  
    redirect_to book_path(@book.id), notice: 'Book was successfully updated.'
    else
     render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト
  end

   private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<!--エラーメッセージ-->
<% if @book.errors.any? %>
  <div id="error">
    <div id="error_explanation">
      <%= @book.errors.count %>errors prohibited this book from being saved:
    </div>

<ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
  
   <%= form_with model: @book do |f| %>
  <div id="field">
  <div id="error_title">
      <label>Title</label>
  </div>
   <div id="error_title">
        <%= f.text_field :title %>
    </div>
  </div>
    
    <div id="error_title">
    
      <label>Body</label>
    </div>
    <div id="error_title">
        <%= f.text_area :body %>
    </div>
      <h4>
        <%= f.submit 'Update Book' %>
      </h4>
    
  <% end %>
   
    
    
<% else %>  
<!--エラーメッセージここまで-->

<%= form_with model: @book, url: book_path(@book.id),method: :patch do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>
  <h4>
  <%= f.submit 'Update Book'%>
  </h4>

<h4>
  <td><%= link_to "Show", book_path(@book.id) %><td> |
  <td><%= link_to "Back", books_path %><td>
</h4>
<% end %>
<% end %>

app/views/books/index.html.erb
    <p id="notice"></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>


<h1>投稿一覧</h1>
<% @books.each do |book| %>
<tbody>
 <tr>
  <td><%=book.title %></td>
  <td><%=book.body%></td>
  <td><%= link_to "Show", book_path(book.id) %><td>
  <td><%= link_to "Edit", edit_book_path(book.id) %><td>
  <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
 </tr>
<% end %>

  </tbody>
</table>


<h2>New book</h2>

<!--エラーメッセージ-->
<% if @book.errors.any? %>
  <div id="error">
    <div id="error_explanation">
      <%= @book.errors.count %>errors prohibited this book from being saved:
    </div>

<ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
  
   <%= form_with model: @book do |f| %>
  <div id="field">
  <div id="error_title">
      <label>Title</label>
  </div>
   <div id="error_title">
        <%= f.text_field :title %>
    </div>
  </div>
    
    <div id="error_title">
    
      <label>Body</label>
    </div>
    <div id="error_title">
        <%= f.text_area :body %>
    </div>
      <h4>
        <%= f.submit 'Create Book' %>
      </h4>
    
  <% end %>
   
    
    
<% else %>  
<!--エラーメッセージここまで-->
  
  
  <%= form_with model: @book do |f| %>
      <label>Title</label>
 
        <%= f.text_field :title %>
  
 
    
      <label>Body</label>
  
        <%= f.text_area :body %>
      <h4>
        <%= f.submit 'Create Book' %>
      </h4>
    
  <% end %>
<% end %>
  </body>
</html>

app/views/books/new.html.erb
<h1>新規投稿</h1>

<!-- form_with部分 -->
<%= form_with model: @book do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<div class="flash-notifications">
  <% flash.each do |key, value| %>
   <%= content_tag(:div, value, class: key) %>
  <% end %>
</div>

<p>
  <strong>Title:</strong>
    <%= @book.title %>
</p>

<p>
  <strong>Body:</strong>
    <%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path(@book.id) %> |
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="sTVjZDMr1pWfDUwzL1GvQ/g1YQTQVQ2rKahXHxG7Nmv/1NTC1ujjntx8mlQ9EekByAZW5awGXAeW9d10hb61hA==" />

    <link rel="stylesheet" media="all" href="/assets/application-d12397cbc3a266ce5a99f7b588223090c55ca04a439953bb5f9304395de93fc3.css" data-turbolinks-track="reload" />
    <script src="/assets/application-114264dd93c8ff30e4335b71eed7949d66c4e7a8eb62e2de6284c046fe07104b.js" data-turbolinks-track="reload"></script>
  </head>

  <body>
    <h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<p><a href="/books">start</a></p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>